// This file is generated by scripts/generate-content-registry.mjs.
// Do not edit it directly.
import type { ContentReference } from "./content-metadata";

export const contentReferences = [
  {
    type: "blog",
    slug: "local-llm-journey",
    href: "/blog/local-llm-journey",
    sourcePath: "content/blog/local-llm-journey/index.mdx",
    metadata: {"title":"Why local models keep pulling me in","description":"A reflection on local LLMs, unfinished thoughts, and the pull toward more private, cost-aware AI workflows.","publishedAt":"2026-07-19","status":"published","tags":["LLM","local-ai","privacy","workflow"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":2}},
  },
  {
    type: "blog",
    slug: "welcome",
    href: "/blog/welcome",
    sourcePath: "content/blog/welcome/index.mdx",
    metadata: {"title":"Opening the workshop","description":"Why I am starting this site as a place for writing, experiments, and learning in public.","publishedAt":"2026-07-18","status":"published","tags":["meta","nextjs","mdx","introduction"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":1}},
  },
  {
    type: "lab",
    slug: "content-architecture",
    href: "/lab/content-architecture",
    sourcePath: "content/lab/content-architecture/index.mdx",
    metadata: {"title":"From MDX files to interactive pages","description":"How this site turns repo-owned MDX, metadata, generic routes, and TSX demos into blog and lab pages.","publishedAt":"2026-07-18","status":"published","tags":["nextjs","mdx","content"],"platform":"nextjs","labStatus":"active","series":{"slug":"building-the-workshop","title":"Building the workshop","order":2}},
  },
  {
    type: "lab",
    slug: "sharing-discovery",
    href: "/lab/sharing-discovery",
    sourcePath: "content/lab/sharing-discovery/index.mdx",
    metadata: {"title":"Sharing and discovery for a content-first site","description":"Exploring better previews, metadata, feeds, and Markdown formats for both readers and AI tools.","publishedAt":"2026-07-18","status":"draft","tags":["sharing","seo","markdown","discoverability"],"platform":"general","labStatus":"planned"},
  },
  {
    type: "lab",
    slug: "vercel-flags",
    href: "/lab/vercel-flags",
    sourcePath: "content/lab/vercel-flags/index.mdx",
    metadata: {"title":"Vercel Flags with a local fallback","description":"A feature-flag lab that runs locally while documenting how to connect real Vercel Flags.","publishedAt":"2026-07-18","status":"draft","tags":["flags","vercel","experiments"],"platform":"vercel","labStatus":"planned"},
  }
] satisfies ContentReference[];
