// This file is generated by scripts/generate-content-registry.ts.
// Do not edit it directly.
import type { ContentReference } from "./content-metadata";

export const contentReferences = [
  {
    type: "notebook",
    slug: "local-llm-journey",
    href: "/notebook/local-llm-journey",
    sourcePath: "content/notebook/local-llm-journey/index.mdx",
    metadata: {"id":"local-llm-journey","type":"notebook","title":"Why local models keep pulling me in","description":"A reflection on local LLMs, unfinished thoughts, and the pull toward more private, cost-aware AI workflows.","publishedAt":"2026-07-19","updatedAt":"2026-07-19","status":"published","tags":["LLM","local-ai","privacy","workflow"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":3},"related":{"notebook":[],"lab":[]},"featured":false},
  },
  {
    type: "notebook",
    slug: "the-notes-i-never-take",
    href: "/notebook/the-notes-i-never-take",
    sourcePath: "content/notebook/the-notes-i-never-take/index.mdx",
    metadata: {"id":"the-notes-i-never-take","type":"notebook","title":"The notes I never take","description":"Lowering the friction between initial thoughts and useful notes.","publishedAt":"2026-07-29","updatedAt":"2026-07-29","status":"published","tags":["local-ai","notes","workflow","curiosity"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":4},"related":{"notebook":[],"lab":[]},"featured":false},
  },
  {
    type: "notebook",
    slug: "welcome",
    href: "/notebook/welcome",
    sourcePath: "content/notebook/welcome/index.mdx",
    metadata: {"id":"opening-the-workshop","type":"notebook","title":"Opening the workshop","description":"Why I am starting this site as a place for writing, experiments, and learning in public.","publishedAt":"2026-07-18","updatedAt":"2026-07-18","status":"published","tags":["meta","nextjs","mdx","introduction"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":1},"related":{"notebook":[],"lab":[]},"featured":false},
  },
  {
    type: "lab",
    slug: "content-architecture",
    href: "/lab/content-architecture",
    sourcePath: "content/lab/content-architecture/index.mdx",
    metadata: {"id":"content-architecture","type":"lab","title":"From MDX files to interactive pages","description":"How this site turns repo-owned MDX, metadata, generic routes, and TSX demos into Notebook and Lab pages.","publishedAt":"2026-07-18","updatedAt":"2026-07-18","status":"published","tags":["nextjs","mdx","content"],"series":{"slug":"building-the-workshop","title":"Building the workshop","order":2},"related":{"notebook":["opening-the-workshop"],"lab":[]},"featured":false,"project":{"stage":"active","startedAt":"2026-07-18","lastActivityAt":"2026-07-18"}},
  },
  {
    type: "lab",
    slug: "sharing-discovery",
    href: "/lab/sharing-discovery",
    sourcePath: "content/lab/sharing-discovery/index.mdx",
    metadata: {"id":"sharing-discovery","type":"lab","title":"Sharing and discovery for a content-first site","description":"Exploring better previews, metadata, feeds, and Markdown formats for both readers and AI tools.","publishedAt":"2026-07-18","updatedAt":"2026-07-18","status":"draft","tags":["sharing","seo","markdown","discoverability"],"related":{"notebook":[],"lab":[]},"featured":false,"project":{"stage":"exploring","startedAt":"2026-07-18","lastActivityAt":"2026-07-18"}},
  },
  {
    type: "lab",
    slug: "vercel-flags",
    href: "/lab/vercel-flags",
    sourcePath: "content/lab/vercel-flags/index.mdx",
    metadata: {"id":"vercel-flags","type":"lab","title":"Vercel Flags with a local fallback","description":"A feature-flag Lab that runs locally while documenting how to connect real Vercel Flags.","publishedAt":"2026-07-18","updatedAt":"2026-07-18","status":"draft","tags":["flags","vercel","experiments"],"related":{"notebook":[],"lab":[]},"featured":false,"project":{"stage":"exploring","startedAt":"2026-07-18","lastActivityAt":"2026-07-18"}},
  }
] satisfies ContentReference[];
