import fs from "node:fs";
import path from "node:path";
import { z } from "zod";

import { contentMetadataSchema } from "../lib/content-schemas";

const projectRoot = process.cwd();
const contentRoot = path.join(projectRoot, "content");
const outputPath = path.join(projectRoot, "app", "lib", "content.generated.ts");
const metadataOutputPath = path.join(projectRoot, "lib", "content-metadata.generated.ts");

function extractMetadata(source: string, file: string) {
  const marker = "export const metadata =";
  const start = source.indexOf(marker);

  if (start === -1) {
    throw new Error(`${file} is missing exported metadata.`);
  }

  const objectStart = source.indexOf("{", start);
  let depth = 0;

  for (let index = objectStart; index < source.length; index += 1) {
    const character = source[index];

    if (character === "{") {
      depth += 1;
    }

    if (character === "}") {
      depth -= 1;

      if (depth === 0) {
        const objectSource = source.slice(objectStart, index + 1);

        return Function(`"use strict"; return (${objectSource});`)() as unknown;
      }
    }
  }

  throw new Error(`${file} has an unterminated metadata object.`);
}

function formatValidationIssues(error: z.ZodError) {
  return error.issues
    .map((issue) => `metadata.${issue.path.join(".") || "root"}: ${issue.message}`)
    .join("\n");
}

function validateMetadata(metadata: unknown, sourcePath: string) {
  const parsed = contentMetadataSchema.safeParse(metadata);

  if (!parsed.success) {
    throw new Error(`Invalid metadata in ${sourcePath}:\n${formatValidationIssues(parsed.error)}`);
  }

  return parsed.data;
}

function getEntries(collection: "notebook" | "lab") {
  const collectionRoot = path.join(contentRoot, collection);

  if (!fs.existsSync(collectionRoot)) {
    return [];
  }

  return fs
    .readdirSync(collectionRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .filter((entry) => fs.existsSync(path.join(collectionRoot, entry.name, "index.mdx")))
    .map((entry, index) => {
      const filePath = path.join(collectionRoot, entry.name, "index.mdx");
      const sourcePath = `content/${collection}/${entry.name}/index.mdx`;
      const source = fs.readFileSync(filePath, "utf8");

      return {
        slug: entry.name,
        source,
        sourcePath,
        metadata: validateMetadata(extractMetadata(source, sourcePath), sourcePath),
        componentName: `${collection}${index}Component`,
        metadataName: `${collection}${index}Metadata`,
        importPath: `@/content/${collection}/${entry.name}/index.mdx`,
      };
    })
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

const notebookEntries = getEntries("notebook");
const labEntries = getEntries("lab");

type ContentEntry = ReturnType<typeof getEntries>[number];

function renderImports(entries: ContentEntry[]) {
  return entries
    .map(
      (entry) =>
        `import ${entry.componentName}, { metadata as ${entry.metadataName} } from ${JSON.stringify(
          entry.importPath,
        )};`,
    )
    .join("\n");
}

function renderEntry(entry: ContentEntry, metadataType: string) {
  return `  {
    slug: ${JSON.stringify(entry.slug)},
    sourcePath: ${JSON.stringify(entry.sourcePath)},
    source: ${JSON.stringify(entry.source)},
    module: {
      default: ${entry.componentName},
      metadata: ${entry.metadataName} as ${metadataType},
    },
  }`;
}

const content = `// This file is generated by scripts/generate-content-registry.ts.
// Do not edit it directly.
import type { LabMetadata, NotebookEntryMetadata } from "./content";

${renderImports([...notebookEntries, ...labEntries])}

export const notebookContent = [
${notebookEntries.map((entry) => renderEntry(entry, "NotebookEntryMetadata")).join(",\n")}
];

export const labContent = [
${labEntries.map((entry) => renderEntry(entry, "LabMetadata")).join(",\n")}
];
`;

fs.writeFileSync(outputPath, content);

function renderMetadataEntries(type: "notebook" | "lab", entries: ContentEntry[]) {
  return entries
    .map(
      (entry) => `  {
    type: ${JSON.stringify(type)},
    slug: ${JSON.stringify(entry.slug)},
    href: ${JSON.stringify(`/${type}/${entry.slug}`)},
    sourcePath: ${JSON.stringify(entry.sourcePath)},
    metadata: ${JSON.stringify(entry.metadata)},
  }`,
    )
    .join(",\n");
}

const metadataContent = `// This file is generated by scripts/generate-content-registry.ts.
// Do not edit it directly.
import type { ContentReference } from "./content-metadata";

export const contentReferences = [
${renderMetadataEntries("notebook", notebookEntries)},
${renderMetadataEntries("lab", labEntries)}
] satisfies ContentReference[];
`;

fs.writeFileSync(metadataOutputPath, metadataContent);
